services:
  - docker

env:
  - ODL_VERSION=0.9.0
  - ODL_VERSION=0.9.1
  - ODL_VERSION=0.9.2
  - ODL_VERSION=0.9.3
  - ODL_VERSION=0.10.0
  - ODL_VERSION=0.10.1
  - ODL_VERSION=0.10.2
  - ODL_VERSION=0.10.3
  - ODL_VERSION=0.11.0
  - ODL_VERSION=0.11.1
  - ODL_VERSION=0.11.2
  - ODL_VERSION=0.11.3
  - ODL_VERSION=0.11.4
  - ODL_VERSION=0.12.0
  - ODL_VERSION=0.12.1
  - ODL_VERSION=0.12.2
  - ODL_VERSION=0.13.0
  - ODL_VERSION=0.13.1

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker build --build-arg ODL_VERSION -t sfuhrm/opendaylight:latest .

deploy:
  provider: script
  script: docker push sfuhrm/opendaylight:latest
  on:
    branch: master
