name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ODL_VERSION:
        - 0.8.0
        - 0.8.1
        - 0.8.2
        - 0.8.3
        - 0.8.4
        - 0.9.0
        - 0.9.1
        - 0.9.2
        - 0.9.3
        - 0.10.0
        - 0.10.1
        - 0.10.2
        - 0.10.3
        - 0.11.0
        - 0.11.1
        - 0.11.2
        - 0.11.3
        - 0.11.4
        - 0.12.0
        - 0.12.1
        - 0.12.2
        - 0.13.0
        - 0.13.1
        - 0.13.2
        - 0.13.3
        - 14.0.0

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stephanfuhrmannionos/opendaylight:${{ matrix.ODL_VERSION }}
          build-args: ODL_VERSION=${{ matrix.ODL_VERSION }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
