name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        -
          TAG: latest
          ODL_VERSION: 0.13.3
          PARENT_IMAGE: "openjdk:11-jre-slim-buster"
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.13.3/opendaylight-0.13.3.tar.gz"
        -
          TAG: 0.13.3
          ODL_VERSION: 0.13.3
          PARENT_IMAGE: "openjdk:11-jre-slim-buster"
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.13.3/opendaylight-0.13.3.tar.gz"

        -
          TAG: 0.13.2
          ODL_VERSION: 0.13.2
          PARENT_IMAGE: "openjdk:11-jre-slim-buster"
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.13.2/opendaylight-0.13.2.tar.gz"

        -
          TAG: 0.13.1
          ODL_VERSION: 0.13.1
          PARENT_IMAGE: "openjdk:11-jre-slim-buster"
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.13.1/opendaylight-0.13.1.tar.gz"

        -
          TAG: 0.13.0
          ODL_VERSION: 0.13.0
          PARENT_IMAGE: "openjdk:11-jre-slim-buster"
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.13.0/opendaylight-0.13.0.tar.gz"
  
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stephanfuhrmannionos/opendaylight:${{ matrix.TAG }}
          build-args: |
            ODL_VERSION=${{ matrix.ODL_VERSION }}
            PARENT_IMAGE=${{ matrix.PARENT_IMAGE }}
            DISTRIBUTION_URL=${{ matrix.DISTRIBUTION_URL }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
