name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  JDK8: "openjdk:8-jre-slim-buster"
  JDK11: "openjdk:11-jre-slim-buster"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        -
          TAG: latest
          ODL_VERSION: 0.13.3
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.13.3/opendaylight-0.13.3.tar.gz"
        -
          TAG: 0.13.3
          ODL_VERSION: 0.13.3
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.13.3/opendaylight-0.13.3.tar.gz"

        -
          TAG: 0.13.2
          ODL_VERSION: 0.13.2
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.13.2/opendaylight-0.13.2.tar.gz"

        -
          TAG: 0.13.1
          ODL_VERSION: 0.13.1
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.13.1/opendaylight-0.13.1.tar.gz"

        -
          TAG: 0.13.0
          ODL_VERSION: 0.13.0
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.13.0/opendaylight-0.13.0.tar.gz"

        -
          TAG: 0.12.2
          ODL_VERSION: 0.12.2
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.12.2/opendaylight-0.12.2.tar.gz"

        -
          TAG: 0.12.1
          ODL_VERSION: 0.12.1
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.12.1/opendaylight-0.12.1.tar.gz"
        -
          TAG: 0.12.0
          ODL_VERSION: 0.12.0
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.12.0/opendaylight-0.12.0.tar.gz"
        -
          TAG: 0.11.4
          ODL_VERSION: 0.11.4
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.11.4/opendaylight-0.11.4.tar.gz"
        -
          TAG: 0.11.3
          ODL_VERSION: 0.11.3
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.11.3/opendaylight-0.11.3.tar.gz"
        -
          TAG: 0.11.2
          ODL_VERSION: 0.11.2
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.11.2/opendaylight-0.11.2.tar.gz"
        -
          TAG: 0.11.1
          ODL_VERSION: 0.11.1
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.11.1/opendaylight-0.11.1.tar.gz"
        -
          TAG: 0.11.0
          ODL_VERSION: 0.11.0
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.11.0/opendaylight-0.11.0.tar.gz"
        -
          TAG: 0.10.3
          ODL_VERSION: 0.10.3
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.10.3/opendaylight-0.10.3.tar.gz"
        -
          TAG: 0.10.2
          ODL_VERSION: 0.10.2
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.10.2/opendaylight-0.10.2.tar.gz"
        -
          TAG: 0.10.1
          ODL_VERSION: 0.10.1
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.10.1/opendaylight-0.10.1.tar.gz"
        -
          TAG: 0.10.0
          ODL_VERSION: 0.10.0
          PARENT_IMAGE: $JDK11
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.10.0/opendaylight-0.10.0.tar.gz"
        -
          TAG: 0.9.3
          ODL_VERSION: 0.9.3
          PARENT_IMAGE: $JDK8
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.9.3/opendaylight-0.9.3.tar.gz"
        -
          TAG: 0.9.2
          ODL_VERSION: 0.9.2
          PARENT_IMAGE: $JDK8
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.9.2/opendaylight-0.9.2.tar.gz"
        -
          TAG: 0.9.1
          ODL_VERSION: 0.9.1
          PARENT_IMAGE: $JDK8
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.9.1/opendaylight-0.9.1.tar.gz"
        -
          TAG: 0.9.0
          ODL_VERSION: 0.9.0
          PARENT_IMAGE: $JDK8
          DISTRIBUTION_URL: "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/0.9.0/opendaylight-0.9.0.tar.gz"

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stephanfuhrmannionos/opendaylight:${{ matrix.TAG }}
          build-args: |
            ODL_VERSION=${{ matrix.ODL_VERSION }}
            PARENT_IMAGE=${{ matrix.PARENT_IMAGE }}
            DISTRIBUTION_URL=${{ matrix.DISTRIBUTION_URL }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
