name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TAG: [ latest ]
        ODL_VERSION: [ 0.13.3 ]
        PARENT_IMAGE: [ "openjdk:11-jre-slim-buster" ]
        DISTRIBUTION_URL: [ "https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/opendaylight/$ODL_VERSION/opendaylight-$ODL_VERSION.tar.gz" ]

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stephanfuhrmannionos/opendaylight:${{ matrix.TAG }}
          build-args: ODL_VERSION=${{ matrix.ODL_VERSION }},PARENT_IMAGE=${{ matrix.PARENT_IMAGE }},DISTRIBUTION_URL=${{ matrix.DISTRIBUTION_URL }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
